In [30]:
import numpy as np

In [31]:

# Simulate scans for each particle
NP = 10
num_beams = 3
measurement =  np.array([[1, 2, 3]])
# print(measurement)

particle_measurements = np.zeros((NP, num_beams))
    # for i, state in enumerate(self.particles): 
    #     particle_measurements[i] = self.scan_simulator.scan(state)
# print(particle_measurements)



In [32]:
# Importance sampling 
z = particle_measurements - measurement
print(z)
        

[[-1. -2. -3.]
 [-1. -2. -3.]
 [-1. -2. -3.]
 [-1. -2. -3.]
 [-1. -2. -3.]
 [-1. -2. -3.]
 [-1. -2. -3.]
 [-1. -2. -3.]
 [-1. -2. -3.]
 [-1. -2. -3.]]


In [37]:
print(z**2)
np.average(z**2, axis=0) #Average along the vertical axis

[[1. 4. 9.]
 [1. 4. 9.]
 [1. 4. 9.]
 [1. 4. 9.]
 [1. 4. 9.]
 [1. 4. 9.]
 [1. 4. 9.]
 [1. 4. 9.]
 [1. 4. 9.]
 [1. 4. 9.]]


array([1., 4., 9.])

In [40]:
sigma = np.clip(np.sqrt(np.average(z**2, axis=0)), 0.01, 10)
weights =  np.exp(-z ** 2 / (2 * sigma ** 2))
Finalweights = np.prod(weights, axis=1)
print(sigma)
print(weights)
print(Finalweights)

        

[1. 2. 3.]
[[0.60653066 0.60653066 0.60653066]
 [0.60653066 0.60653066 0.60653066]
 [0.60653066 0.60653066 0.60653066]
 [0.60653066 0.60653066 0.60653066]
 [0.60653066 0.60653066 0.60653066]
 [0.60653066 0.60653066 0.60653066]
 [0.60653066 0.60653066 0.60653066]
 [0.60653066 0.60653066 0.60653066]
 [0.60653066 0.60653066 0.60653066]
 [0.60653066 0.60653066 0.60653066]]
[0.22313016 0.22313016 0.22313016 0.22313016 0.22313016 0.22313016
 0.22313016 0.22313016 0.22313016 0.22313016]


In [42]:
# Normalize weights
Finalweights = Finalweights/ np.sum(Finalweights)
print(Finalweights)

[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]


In [ ]:
 # Resampling
proposal_indices = np.random.choice(self.particle_indices, self.NP, p=self.weights)
self.proposal_distribution = self.particles[proposal_indices,:]